# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0BN4NmCWg-hySP7UXlHLKMAQUZZFA37
"""

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr, type(arr))

# see data type
print(arr.dtype)

# shape of array
print(arr.shape)

# create 2d array
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d.shape)

# create arr in buit in method


arr1 = np.zeros(3, dtype="int64") # 2d ((3,3))
print(arr1)

arr2 = np.ones(5)
print(arr2)

arr3 = np.full((2,2),7) #(2,7)
print(arr3)

arr4 = np.eye(3)
print(arr4)

arr5 = np.arange(1,10,2)# create arr in range (start, end, distance)
print(arr5)

arr6 = np.linspace(1, 100, 20)# rendomly create arr of 20 in betw 1 to 100 number
print(arr6)

# properties

arr = np.array([[1,2,3,5,4,6,7], [1,2,3,5,4,6,7]])

print(arr.shape) # shape in m x n  raw and column

print(arr.size) # size of arr 7

print(arr.dtype) # arr data type int64

print(arr.ndim)# arra dimenssion 1d

float_arr = arr.astype(np.float64)# change data type \\ int to float
print(float_arr, type(float_arr))

# opereation
arr = np.array([[1,2,3,5,4,6,7], [1,2,3,5,4,6,7]])

# 1. reshaping
print(arr.shape)

reshape = arr.reshape(7,2)
print(reshape)

#flatten (convert to 1d array)
flatten = arr.flatten()
print()
print(flatten)

#indexing
arr = np.array([1,2,3,5,4,6,7]) #for 1d
print()
print(arr[4])

arr = np.array([[1,2,3,5,4,6,7], [1,2,3,5,4,6,7]])# for 2d
print()
print(arr[1][1])# arr[raw][column]

# fancY indexing
arr = np.array([1,2,3,5,4,6,7])
index = [6,5,4]
print()
print(arr[index])

# boolean indexing or masking
arr = np.array([1,2,3,5,4,6,7])
print()
print(arr[arr%2 == 0])


#slicing (did not take extra memory)
arr = np.array([1,2,3,5,4,6,7])
  ##[start: end: step] / [  : end: step] / [start: end]
#sub_arr = arr.[start: end: step]
print()
print(arr[1:6:2])

"""Day-2"""

# ayyay copy
arr = np.array([1,2,3,5,4,6,7])
arr_copy = arr.copy()
print(arr_copy)

# Data type in numpy

arr = np.array([1,2,3,5,4,6,7])
print(arr, arr.dtype)

arr = np.array([1.0,2,3,5,4,6,7])
print(arr, arr.dtype)

# axes in multi dimentional array
# 3d array
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

# sum of column
sum_of_column = np.sum(arr2d, axis=0)
print(sum_of_column)

#slicing in axis sum
print(arr2d[0:1][1:1])

# 3d rray
arr3d = np.array([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]]]) # 2 x 3 x 2

# in this array there is 2 2d array and each 2d array have 3x2 shape

print(arr3d)
#print(arr3d.ndim)

#to find the 4
print(arr3d[0,1,1])

#slicing in 3d array
print(arr3d[:,0,:]) # 1st raw of every 2d array
print(arr3d[:,:,0]) # 1st colum of every 2d array

# vectirization
arr1 = np.array([1,2,3,5,4,6,7])
arr2 = np.array([1,2,3,5,4,6,7])
print(arr1+arr2)
print(arr1*3)

# normalization

arr = np.array([[1,2], [3,4]])
mean =np.mean(arr)
std_dev = np.std(arr)
print(f"normalization arr \n {(arr-mean)/std_dev}")

"""**mathematical function**"""

# 1. aggrigate function
#2. Power Functions
#3. Log & Exponential Functions
#4. Rounding Functions
#5. Miscellaneous Functions