# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tnagsyp2nZe_CSCcOZ5tFTglzVSkQsR
"""

import pandas as pd
import numpy as np

# data frame (2d labeled array)
info={
    "name":["rahul","hari","jadu"],
    "cgpa":[6.7,89.5,6.9]
}

df = pd.DataFrame(info)
print(df)
print(df.index) # return index of data
print(df.columns)# returns the columns of the data frame

df = pd.DataFrame([["a", 12],["b", 13],["c", 23]], columns=["name", "age"])
print(df)

# create data frame from numpy

np_arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(np_arr, columns=["a", "b", "c"])
print(df)

# series(1d labeld data)
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

print(s[0])

# load file csv / escel/ json

df = pd.read_csv("employee_data.csv")
print(df)

print("-----------------------------------------")

#df = pd.read_json("employee_data.json")
#print(df)

# data frame methods helps in EDA

#print(df.head()) # return 1st 5 raw  df.head(10) for 1st 10 raw

#print(df.tail()) # return last 5 raw df.tail(10) for last 10 raw

#print(df.sample()) # return random 1 raw  df.sample(4) return random 4 raw

#print(df.info()) # return the basic info about the data frame

#df.shape # return the number of raw and column

#df.describe()  # return the mathematical description of the numerical column of the data

#df.columns # return the columns

#df.nunique() # return thr number of unique value in a column

# real data set

df = pd.read_csv("globalAirQuality.csv")
df

df.head()

df.shape

df.info()

df.describe()

df.head()

# selecting data


  # ---------column--------------
df["column"] # return the the column values with index number
df[["city","aqi", "temperature", "humidity"]]

   # --------------raw----------------
    #1.loc
df.loc[index] # return the index number's raw
df.loc[start index:end index] # retyrn in range and end index in inclusive


    #2.iloc
df.iloc[index] # return the index/label number's raw
df.loc[start index:end index] # retyrn in range and end index in exclusive

#---------indivisual------------------------

 #loc method
df.loc[0,"aqi"] # [raw index number, column name]
df.loc[0,["city","aqi"]] # [raw index number[column, column name]]

df.loc[0:4,["city","aqi"]] # [raw_start_index_number:raw_end_index_number,[column name, column name]

  # iloc method
df.iloc[0:4,[1,4]] #[raw_start_index_number:raw_end_index_number,[column index, column index]
                   # iloc requirdes the column index infact on numeric no string


# ----------------scaller value--------------------------------

                   # 1.at
df.at[0,"city"]  # [raw index number, column name]

                   # 2.iat
df.iat[0,5]  # [raw index number, column index number] take only numeric same as iloc



city = df["city"].copy() #to avoid changes in real data
city[0] = "baleswar"
city

# Filtering of data

df[ df["aqi"] > 100] # return the data whic have qui more then 100
df[ (df["aqi"] > 100 ) & (df["temperature"] > 30 )] # return the data whic have qui more then 100 and temp more then 20
                                                    # multi condition

          # chaining

df[ df["aqi"] > 100] [["city", "aqi"]] # return the city and aqi which have aqi more then 100


# filtering data using query method
df.query("aqi > 100")# also return the data which have qui more then 100

df.query("aqi > 100 & temperature > 30")# also return the data whic have qui more then 100 and temp more then 20
                                                    # multi condition
        #chaining
df.query("aqi > 100") [["city", "aqi"]]  # also return the city and aqi which have aqi more then 100

        # also support variable method
aqi_value = 100
df.query("aqi > @aqi_value") # also return the data which have qui more then 100

df.head()

